[book]
title = "LuauToolkit Documentation"
authors = ["plainenglish"]
src = "src/"
language = "en"

[build]
create-missing = false

[preprocessor.alerts]
command = "lune run preprocessor"
#[preprocessor.alerts]
#[preprocessor.inline-highlighting]
#default-language = "none"
#[preprocessor.cmdrun]
